services:
  mysql:
    image: mysql:8.4                 # MySQL image
    container_name: mysql-local      # Container name

    environment:
      MYSQL_ROOT_PASSWORD: password  # Root password
      MYSQL_DATABASE: users_db       # Database name
      MYSQL_USER: user               # Application user
      MYSQL_PASSWORD: password       # Application password

    ports:
      - "3306:3306"                  # Host machine : Container

    volumes:
      - mysql_data:/var/lib/mysql    # Host machine : Container

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .                         # Build from ./Dockerfile
    container_name: backend-local

    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=users_db;User=user;Password=password;"

    ports:
      - "5097:8080"                  # Host machine : Container

    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend                # Build from ./frontend/Dockerfile
    container_name: frontend-local

    ports:
      - "5173:80"                    # Host machine : Container

    depends_on:
      - backend

volumes:
  mysql_data:                        # Create a Docker volume

# docker-compose.yml: runs MySQL, the .NET backend API, and the React frontend together.
